🏅 OOP school library: add Person, Student and Teacher classes 🏅
kambereBr/school-library pull request #1
Opened 2023-10-02 22:11 UTC by kambereBr

## 📝 General requirements

- ✅ Used the correct GitFlow.
- ✅ Created a class `Person` with  the following:
  - Instance vars: `@id`, `@name`, and `@age`.
  - Constructor with `name`,  `age`, and `parent_permission` as parameter. `name` and `parent_permission` are optional and have default values of `"Unknown"` and `true`.
  - Getters for `@id`, `@name`, and `@age`.
  - Setters for `@name` and `@age`.
  - Private method `of_age?` that returns `true` if `@age` is greater or equal to 18 and `false` otherwise.
  - Public method `can_use_services?` that returns `true` if person is of age or if they have permission from parents.
- ✅ Created a class `Student` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@classroom` and a parameter for it.
  - Method `play_hooky` that returns `"¯\(ツ)/¯"`.
- ✅ Createa a class `Teacher` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@specialization` and a parameter for it.
  - Override `can_use_services?` so it always returns `true`.
- ✅ Each class should be saved in a separate file.

2023-10-02 22:32 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @kambereBr👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitFlow correctly 👍🏽
✅ Created a class Person✔
✅ Created a class Student✔
✅ Created a class Teacher✔
✅ Each class is saved in a separate file✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-02 22:32 UTC, Johnadibe commented on app/models/person.rb
> +  end
> - [ ] According to the project requirements, please include the setter attributes for `@name` and `@age`, and also ensure the presence of the getter attribute for @id. Incorporating these changes will ensure your strict adherence to the project guidelines.
> 
> ![set](https://github.com/kambereBr/school-library/assets/40009354/88ac818d-75e6-4bf7-856a-7dffcfcb5f70)
> 
> You can use the below as an instance:
> 
> ```
> class Person
> attr_accessor :name, :age
> attr_reader :id
> 
>   def initialize(age, name = 'Unknown', parent_permission: true)
>     @id = Random.rand(1..1000)
>     @name = name
>     @age = age
>     @parent_permission = parent_permission
>   end
> end
> ```

2023-10-02 23:02 UTC, kambereBr commented on app/models/person.rb
> +  end
https://github.com/kambereBr/school-library/blob/f142eb2201fe3957c0dca42302c8d4e53c2bafdb/app/models/person.rb#L13-L14

Thanks dear @Johnadibe for your review.
`setters` and `getters` already exists in the class Person. 
Thanks.

2023-10-02 23:51 UTC, skyv26 requested changes
## Hi @kambereBr, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTY5MTMxNDUzNWFmNjU5MmFjOWZjY2IyMDIyY2RhNWFlYmU4NjdlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Xfb7kQ0VhUIrpiuGx1/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-02 23:51 UTC, skyv26 commented on app/models/student.rb
> +  end
- [ ] Please adhere to the project requirement. According to this, you should extend the functionality of the Person using the Student class inherited from the Person. You can even see that you passed the `age`, `name` and `true` attributed but from where the `age` and `name` are coming from you haven't specified that and the answer is you should also have to add the `classroom`, `age`, `name` and `parent_permission` attribute in the constructor.
![image](https://github.com/kambereBr/school-library/assets/66476329/389cc3d6-af21-4a62-9706-520988713fcf)

2023-10-02 23:51 UTC, skyv26 commented on app/models/person.rb
> +    of_age? || @parent_permission ? true : false
- [OPTIONAL] here you don't need the `? true: false` because as soon as `of_age` is true then it will automatically return true even without checking the `@parent_permission`. If your `of_age` is false then it check the `@parent_permission`. Once the both variable evaluated based on the `OR` operator. It will result in `either` or `false` so you don't need to mention the things explicitly. 

```suggestion
    of_age? || @parent_permission
```

2023-10-02 23:53 UTC, skyv26 commented
## This comment was missed out so please consider it too

- [ ] Please adhere to the project requirement. According to this, you should extend the functionality of the Person using the Teacher class inherited from the Person. You can even see that you passed the `age`, `name` and `true` attributed but from where the `age` and `name` are coming from you haven't specified that and the answer is you should also have to add the `specialization`, `age`, `name` and `parent_permission` attribute in the constructor.
![image](https://github.com/kambereBr/school-library/assets/66476329/db34223a-4ef3-4f90-a24a-9d7c4b58954e)

2023-10-03 18:32 UTC, kambereBr commented on app/models/student.rb
> +  end
Thanks dear @skyv26 for your precious review 👏

2023-10-03 18:58 UTC, ademibowale approved these changes
Hi @kambereBr , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️
- Create class Person, Student and Teacher ✔️
- Getters for @id, @name, and @age..✔️
- Setters for @name and @age ✔️
- Descriptive commit messages ✔️ 
- Good use of Gitflow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 19:13 UTC, kambereBr commented
Thanks dear @ademibowale 👏

2023-10-03 19:13 UTC, merged