🏅 OOP school library: set up associations 🏅
kambereBr/school-library pull request #3
Opened 2023-10-05 21:19 UTC by kambereBr

## 📝 General requirements

- ✅ No linters errors
- ✅ Used the correct GitFlow.
- ✅ Created a class `Classroom` with `@label` instance variable
- ✅ Created the `has-many`/`belongs-to` relationship between `Classroom` and `Student`. 
- ✅ Created a class `Book` with `@title` and `@author` instance variables
- ✅ Created a class `Rental` with `@date` instance variable and  `Book` and `Person` set in
- ✅ Created the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`.

2023-10-05 22:15 UTC, OyePriscilla requested changes
Hi @kambereBr 👏 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Implemented a program using the command line. ✔️ 
Set up associations between classes and objects. ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 22:15 UTC, OyePriscilla commented on app/models/book.rb
> +
- [ ] Kindly please implement *Getters and Setters for @rentals in accordance to the requirement , a setter method is used to modify or set the value of an attribute. 👍

- [ ] Kindly implement the logic require to add a rental for a book  this method supposed to associate a book with a rental date.


<img width="533" alt="Untitled" src="https://github.com/kambereBr/school-library/assets/103386183/a52c43a7-a4b5-4b5b-a14a-0319e75a6f37">

2023-10-05 22:15 UTC, OyePriscilla commented on app/models/person.rb
> +  attr_reader :id, :rental
- [ ] Kindly please implement *Getters and Setters for @rentals in accordance to the requirement , a setter method is used to modify or set the value of an attribute. 👍

- [ ] Kindly implement the logic require to add a rental for a person,  this method supposed to associate a book with a rental date.


<img width="533" alt="Untitled" src="https://github.com/kambereBr/school-library/assets/103386183/a52c43a7-a4b5-4b5b-a14a-0319e75a6f37">

2023-10-05 22:15 UTC, OyePriscilla commented on app/models/rental.rb
> +  attr_reader :person, :book
- [ ] Kindly please implement *Getters and Setters for `@person and @book` in accordance to the requirement, a setter method is used to modify or set the value of an attribute. 👍

2023-10-06 17:17 UTC, kambereBr commented on app/models/book.rb
> +
Thanks dear @OyePriscilla for your review 👏

2023-10-06 17:49 UTC, Abenezer-Tilahun requested changes
Hi @kambereBr 

Great job for implemented  the some of the Requirement requested by the previous reviewer   , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linter errors
✔️ Correct Git-Flow
✔️ Good commit messages
✔️ Professional README
✔️ Correctly Create a class Classroom, class Book, a class Rental with their instance variables.
✔️ Correctly Create the has-many/belongs-to relationship between Classroom and Student.

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 17:49 UTC, Abenezer-Tilahun commented on app/models/book.rb
> +  attr_reader :rental
- [ ] As suggested by the previous reviewer Kindly I recommend you to set `*Getters and Setters for @rentals` instead of setting only  `attr_reader for @rentals` because when you set up `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`, A book should have many rentals so in `attr_accessor` provides both read and write access to an instance variable, while attr_reader only provides read access. So kindly Adjust like the below sample.
```

attr_accessor :title, :author, :rentals

```

2023-10-06 17:49 UTC, Abenezer-Tilahun commented on app/models/person.rb
> +  attr_reader :id, :rental
- [ ] As suggested by the previous reviewer Kindly I recommend you to set `*Getters and Setters for @rentals` instead of setting only  `attr_reader for @rentals` because when you set up `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`, A person should have many rentals: So in `attr_accessor` provides both read and write access to an instance variable, while `attr_reader `only provides read access. So kindly Adjust like the below sample.

```
 attr_reader :id
attr_accessor :age, :name, :rentals



```

2023-10-06 18:28 UTC, kambereBr commented on app/models/book.rb
> +  attr_reader :rental
Thanks dear @Abenezer-Tilahun for your review 👏

2023-10-06 18:39 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @kambereBr👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented all changes requested by the previous reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 18:42 UTC, kambereBr commented
Thanks dear @Johnadibe for your review 👏

2023-10-06 18:42 UTC, merged